const APP_NAME = 'SnapType';
const TOGGLE_SHORTCUT_ACCELERATOR = 'Control+Shift+Space';
const TOGGLE_SHORTCUT_DISPLAY = 'Ctrl+Shift+Space';
const BUFFER_SIZE = 30;
const ACTIVE_APP_POLL_INTERVAL_MS = 300;
const EXPANSION_SETTLE_DELAY_MS = 28;
const HOOK_RESUME_DELAY_MS = 220;

module.exports = {
  ACTIVE_APP_POLL_INTERVAL_MS,
  APP_NAME,
  BUFFER_SIZE,
  EXPANSION_SETTLE_DELAY_MS,
  HOOK_RESUME_DELAY_MS,
  TOGGLE_SHORTCUT_ACCELERATOR,
  TOGGLE_SHORTCUT_DISPLAY
};
